import Head from "next/head";
import HomePage from "../components/HomePage";
import { client } from "../lib/client";

export default function Home({ res }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage res={res} />
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = "*[_type=='product']";
  const res = await client.fetch(query);

  return {
    props: {
      res: res,
    },
  };
};
